swagger: "2.0"
info:
  description: "Technical Test Inc. is a clothing company that recently had a big commercial success. This describe REST API with third parties for validation and logging"
  version: "1.0.0"
  title: "Swagger Technical Test Inc."
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "crstn.salvati@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:9000"
basePath: "/"
tags:
- name: "payment"
  description: "clothing store payment"
- name: "log"
  description: "error log entity"
- name: "wefox"
  description: "wefox. Insurance. But simple."
  externalDocs:
    description: "wefox Group engineer Challenge"
    url: "https://www.wefox.com/"
schemes:
- "https"
- "http"
paths:
  /log:
    post:
      tags:
      - "log"
      summary: "Create log entity"
      description: ""
      operationId: "createLogEntity"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created log object"
        required: true
        schema:
          $ref: "#/definitions/Log"
      responses:
        default:
          description: "successful operation"
        "405":
          description: "Invalid input"
  /payment:
    post:
      tags:
      - "payment"
      summary: "Send payment request"
      description: ""
      operationId: "sendPaymentEntity"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created payment object"
        required: true
        schema:
          $ref: "#/definitions/Payment"
      responses:
        default:
          description: "successful operation"
        "405":
          description: "Invalid input"
definitions:
  Payment:
    type: "object"
    properties:
      paymentId:
        type: "string"
      accountId:
        type: "integer"
        format: "int32"
      paymentType:
        type: "string"
      creditCard:
        type: "string"
      amount:
        type: "integer"
        format: "int32"
  Log:
    type: "object"
    properties:
      paymentId:
        type: "string"
      errorType:
        type: "string"
      errorDescription:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"